permalink: pretty

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/:num/"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "sanko"

exclude:
  - help.rb
