permalink: pretty

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  debug: false
  collection: "posts"
  per_page: 5
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  trail:
    before: 1
    after: 1

autopages:
  enabled: true
  categories:
    layouts:
      - "list.html"
    title: "Posts in :cat"
    permalink: "/category/:cat"
  tags:
    layouts:
      - "list.html"
    title: "Posts tagged with :tag"
    permalink: "/tag/:tag"
  collections:
    enabled: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "sanko"

exclude:
  - help.rb
